s3: 
  bucket_name: "pharma-physician-conversion"
  file_path: "preprocessed/preprocessed_df.csv"
  aws_region : 'ap-south-1'  # Replace with your desired AWS region
  model_variable_list_file_path: "preprocessed/top_n_list_selectKbest.pkl"
  df_inference_set : "processed_dataframes/df_inference.csv"
  df_validation_set : "processed_dataframes/df_validation.csv"
  df_training_set : "processed_dataframes/df_train.csv"


train_model_parameters:
  inference_size : 0.1 #As it is a demo project we are creating Inference set here for infernece pipeline
  val_size : 0.2
  model_params : {'colsample_bytree': 0.8011137517906433, 
                  'gamma': 0.0003315092691686855,
                  'max_depth': 7, 'reg_alpha': 0.20064996416845873, 
                  'subsample': 0.19265865309365698}
  
  
feature_store:
    table_name: "physician_conversion_feature_table"
    lookup_key: ['NPI_ID', 'HCP_ID']
    label : ['TARGET']
    description : "Physician conversion features- claims, procedure, demographic, etc."

mlflow:
    experiment_name:  "dbfs:/Shared/dbx/projects/physician_conversion_mlops"
    mlflow_run_name : "physician_conversion_experiments"

